### ISSUE TITLE
bug: 无法打包为生产模式

### ISSUE THREAD

**Issue by HyperLife1119** [wszgrcy/angular-miniprogram#1]
重现步骤：
执行 `ng build --configuration production --aot --build-optimizer`

```log
[error] TypeError: Cannot create property 'chunks' on boolean 'false'
    at WebpackConfigurationChange.<anonymous> (xxx\angular-miniprogram-template\node_modules\angular-miniprogram\builder\webpack-configuration-change.js:99:64)
    at Generator.next (<anonymous>)
    at fulfilled (xxx\angular-miniprogram-template\node_modules\angular-miniprogram\builder\webpack-configuration-change.js:24:58)
```

**Comment by HyperLife1119** [comment]
是打开了 buildOptimizer 导致的

**Comment by wszgrcy** [comment]
> 是打开了 buildOptimizer 导致的

![image](https://user-images.githubusercontent.com/9607121/132928442-3f9da052-570a-48d0-9d0d-99d3311f8380.png)
你可以先通过修改这个配置使打包成功
目前正常情况下,只需要添加`vendorChunk`即可,但是我修改了下全局样式的后缀,导致了和ng计算包大小警告的那个插件有冲突,可以先把配置删了跑起来,我再排除下原因

**Comment by wszgrcy** [comment]
https://github.com/wszgrcy/angular-miniprogram/commit/1acec341e839d9032289b33ab6f231d432bf180c
